name: fair_maturity_indicators
channels:
  - conda-forge
dependencies:
  - python=3.7.3
  - pandas=0.24.2
  - numpy=1.16.2
  - matplotlib=3.0.3
  - simplegeneric # for rpy2
  - watermark # for dependences
  # R packages
  - rpy2
  - r-base=3.6.1
  - r-ggplot2
