name: fair_maturity_indicators
channels:
  - conda-forge
dependencies:
  - python=3.7.3
  - pandas=0.24.2
  - watermark # for dependences
  - simplegeneric # for rpy2
  - rpy2  
  # R packages
  - r-base=3.6.1
  - r-ggplot2
