name: fair_maturity_indicators
channels:
  - conda-forge
dependencies:
  - python=3.7.1
  - pandas=0.23.4
  - watermark # for dependences
  - simplegeneric # for rpy2
  - rpy2=3.0.4 
  # R packages
  - r-base=3.4.1
  - r-ggplot2
